sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - yarn install

script:
  - yarn test
  - yarn build
  - yarn build:docker

deploy:
  provider: script
  script: docker push unqpdes/todo-list-front
  on:
    branch: dockerized

