sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  # install deps
  - yarn install

script:
  - yarn test
  - yarn build
  # build docker images
  - yarn build:docker
  - docker tag unqpdes/todo-list-front:latest registry.heroku.com/pdes-2018-todo-list-front/web

deploy:
  provider: script
  script: 
    # push to dockerhub
    docker push unqpdes/todo-list-front;
    # push & release in heroku
    docker push registry.heroku.com/pdes-2018-todo-list-front/web;
    heroku container:release web --app pdes-2018-todo-list-front
  on:
    branch: master

